apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 100Gi
    class: isilon-storage-class
    deleteClaim: false
  resources:
    requests:
      memory: 2Gi
      cpu: "500m"
    limits:
      memory: 4Gi
      cpu: "1"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 500Gi
    class: isilon-storage-class
    deleteClaim: false
  resources:
    requests:
      memory: 4Gi
      cpu: "1"
    limits:
      memory: 8Gi
      cpu: "2"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV0
    
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            secretName: kafka-oauth-secret
            key: secret
          validIssuerUri: https://your-keycloak-domain/realms/your-realm
          jwksEndpointUri: https://your-keycloak-domain/realms/your-realm/protocol/openid-connect/certs
          userNameClaim: preferred_username
          enablePlain: true
          tokenEndpointUri: https://your-keycloak-domain/realms/your-realm/protocol/openid-connect/token
    
    authorization:
      type: simple
    
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      num.network.threads: 8
      num.io.threads: 8
    
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "200m"
        limits:
          memory: 512Mi
          cpu: "500m"
    
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "200m"
        limits:
          memory: 512Mi
          cpu: "500m"
  
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
